spring:
  profile:
    active: dev

---
spring:
  profile: dev
  application:
    name: springcloud-config-dev

---
spring:
  profile: test
  application:
    name: springcloud-config-test

---
spring:
  profile: pro
  application:
    name: springcloud-config-pro
